// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAPI.PhoneBook.Data;

namespace WebAPI.PhoneBook.Migrations
{
    [DbContext(typeof(UserContext))]
    [Migration("20220312064327_SeedUserData")]
    partial class SeedUserData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebAPI.PhoneBook.Data.User", b =>
                {
                    b.Property<int>("UUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Company")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UUID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UUID = 1,
                            Company = "Amazon",
                            Location = "USA",
                            Mail = "joh.doe@amazon.com",
                            Name = "John",
                            Phone = "111444",
                            Surname = "Doe"
                        },
                        new
                        {
                            UUID = 2,
                            Company = "Amazon",
                            Location = "USA",
                            Mail = "ricky.more@amazon.com",
                            Name = "Ricky",
                            Phone = "777888",
                            Surname = "More"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
